# Generated by Django 4.0.5 on 2022-07-03 01:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0001_initial'),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='platform',
        ),
        migrations.AddField(
            model_name='contract',
            name='placement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='placements.placement'),
            preserve_default=False,
        ),
    ]
