# Generated by Django 4.0.5 on 2022-07-03 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('contracts', '0002_remove_contract_platform_contract_placement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='advertiser',
        ),
        migrations.AddField(
            model_name='contract',
            name='campaign',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign'),
            preserve_default=False,
        ),
    ]
