# Generated by Django 4.0.5 on 2022-07-10 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
        ('contracts', '0003_remove_contract_advertiser_contract_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='payment_channel_address',
        ),
        migrations.AddField(
            model_name='contract',
            name='channel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='channels.channel'),
        ),
    ]
