# Generated by Django 4.0.5 on 2022-07-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_remove_contract_payment_channel_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='initial_balance',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
