# Generated by Django 4.0.5 on 2022-07-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelstate',
            name='signature',
            field=models.JSONField(null=True),
        ),
    ]
