# Generated by Django 4.0.5 on 2022-07-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_channelstate_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelstate',
            name='balance_advertiser',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='channelstate',
            name='balance_platform',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='channelstate',
            name='seqno_advertiser',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='channelstate',
            name='seqno_platform',
            field=models.IntegerField(default=0),
        ),
    ]
