# Generated by Django 4.0.5 on 2022-07-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_ton_account_seed_profile_ton_account_mnemonic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ton_account_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
